# Generated by Django 3.2.5 on 2021-10-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idvalue',
            old_name='left_prefix',
            new_name='left_p',
        ),
        migrations.RenameField(
            model_name='idvalue',
            old_name='right_prefix',
            new_name='right_p',
        ),
    ]
