# Generated by Django 4.0.1 on 2022-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211025_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idvalue',
            old_name='left_p',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='idvalue',
            old_name='model_name',
            new_name='model_state',
        ),
        migrations.RenameField(
            model_name='idvalue',
            old_name='right_p',
            new_name='right',
        ),
    ]
