// items.js
export const SELECT_ITEM = "SELECT_ITEM"

// nav.js
export const SET_STEP = "SET_STEP"
export const OPEN_EXPLANATION_POPUP = "OPEN_EXPLANATION_POPUP"
export const CLOSE_EXPLANATION_POPUP = "CLOSE_EXPLANATION_POPUP"
export const OPEN_ADVERSARIAL_POPUP = "OPEN_ADVERSARIAL_POPUP"
export const CLOSE_ADVERSARIAL_POPUP = "CLOSE_ADVERSARIAL_POPUP"

// build.js
export const UPLOAD_START = "UPLOAD_START"
export const MODEL_UPLOAD_SUCCESS = "MODEL_UPLOAD_SUCCESS"
export const MODEL_REMOVE_UPLOAD = "MODEL_REMOVE_UPLOAD"
export const WRAPPER_UPLOAD_SUCCESS = "WRAPPER_UPLOAD_SUCCESS"
export const WRAPPER_REMOVE_UPLOAD = "WRAPPER_REMOVE_UPLOAD"
export const DATASET_UPLOAD_SUCCESS = "DATASET_UPLOAD_SUCCESS"
export const DATASET_REMOVE_UPLOAD = "DATASET_REMOVE_UPLOAD"
export const UPLOAD_FAIL = "UPLOAD_FAIL"

export const PARAMS_SET_LEFT_PREFIX = "PARAMS_SET_LEFT_PREFIX"
export const PARAMS_SET_RIGHT_PREFIX = "PARAMS_SET_RIGHT_PREFIX"
export const PARAMS_SET_LABEL = "PARAMS_SET_LABEL"

export const RECORD_START = "RECORD_START"
export const RECORD_READ_SUCCESS = "RECORD_READ_SUCCESS"
export const RECORD_FAIL = "RECORD_FAIL"

export const RECORD_SELECT_RECORDS = "RECORD_SELECT_RECORDS"

export const EXPLANATION_START = "EXPLANATION_START"
export const EXPLANATION_READ_SUCCESS = "EXPLANATION_READ_SUCCESS"
export const EXPLANATION_FAIL = "EXPLANATION_FAIL"

export const ADVERSARIAL_START = "ADVERSARIAL_START"
export const ADVERSARIAL_READ_SUCCESS = "ADVERSARIAL_READ_SUCCESS"
export const ADVERSARIAL_FAIL = "ADVERSARIAL_FAIL"





